name: Test

on:
  push:
    branches:
      master
  pull_request:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  contents: read

jobs:

  build:
    runs-on: ubuntu-latest # should switch to mac to run dmg test, but it's unstable atm
    steps:
    - uses: actions/checkout@v3

    - name: Setup and install deps
      uses: ./.github/actions/setup

    - name: Install pnpm dependencies for pnpm-demo test
      run: cd pkg/node-modules/pnpm-demo/ && pnpm install

    - name: Install npm dependencies for npm-demo test
      run: cd pkg/node-modules/npm-demo/ && npm install
      
    - name: Test
      run: make test

    - name: Build
      run: make build-all
