name: Test

on:
  push:
    branches:
      master
  pull_request:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  contents: read

jobs:
  test-linux:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code repository
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
        with:
          fetch-depth: 1

      - name: Setup Go
        uses: actions/setup-go@v4

      - name: Lint
        run: go test ./...
        