# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "master" ]
  pull_request:
  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Use Node.js 18
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install yarn
      run: npm install -g yarn

    - name: Install pnpm
      run: npm install -g pnpm

    - name: Install pnpm dependencies
      run: cd pkg/node-modules/pnpm-demo/ && pnpm install

    - name: Install npm dependencies
      run: cd pkg/node-modules/npm-demo/ && npm install

    - name: Install yarn dependencies
      run: cd pkg/node-modules/yarn-demo/ && yarn install

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
